http-clients:
  internal:
    api-orden-service-v1:
      base-url: http://api-orden-service-v1/api/v1/ordenes
      timeout: 5s
    api-pagos-service-v1:
      base-url: http://api-pagos-service-v1/api/v1/pagos
      timeout: 5s
    api-pagos-service-v2:
      base-url: http://api-pagos-service-v2/api/v1/pagos
      timeout: 5s
    api-farmacia-service-v1:
      base-url: http://api-farmacia-service-v1/api/v1/farmacias
      timeout: 5s
    api-entrega-service-v1:
      base-url: http://api-entrega-service-v1/api/v1/entrega
      timeout: 5s
  external:
    api-mastercad-service-v1:
      base-url: http://localhost:40017/api/mastercard
      timeout: 5s